"""Battle engine tuning — re-exported from core.settings for backward compatibility."""

from core import settings

# ── Arming / pair lock ──
BATTLE_ARM_MAX_GAP_METERS = settings.BATTLE_ARM_MAX_GAP_METERS
BATTLE_ARM_ABORT_GAP_METERS = settings.BATTLE_ARM_ABORT_GAP_METERS
BATTLE_ARM_ABORT_GRACE_SEC = settings.BATTLE_ARM_ABORT_GRACE_SEC
BATTLE_ARM_MIN_SPEED_KMH = settings.BATTLE_ARM_MIN_SPEED_KMH
BATTLE_ARM_CANCEL_SPEED_KMH = settings.BATTLE_ARM_CANCEL_SPEED_KMH
ARM_SUSTAINED_PROXIMITY_SEC = settings.ARM_SUSTAINED_PROXIMITY_SEC
ARMED_CHAT_COOLDOWN_SEC = settings.ARMED_CHAT_COOLDOWN_SEC

MAX_BATTLE_GAP_METERS = settings.MAX_BATTLE_GAP_METERS
PRESTART_GAP_ABORT_GRACE_SEC = settings.PRESTART_GAP_ABORT_GRACE_SEC
GAP_ABORT_MIN_BOTH_SPEED_KMH = settings.GAP_ABORT_MIN_BOTH_SPEED_KMH
LAUNCH_TIMEOUT_SEC = settings.LAUNCH_TIMEOUT_SEC
FINISHED_COOLDOWN_SEC = settings.FINISHED_COOLDOWN_SEC

# ── Run end / scoring ──
FINISH_LINE_HIGH_SPLINE = settings.FINISH_LINE_HIGH_SPLINE
FINISH_LINE_LOW_SPLINE = settings.FINISH_LINE_LOW_SPLINE
MIN_LAP_PROGRESS_BEFORE_FINISH = settings.MIN_LAP_PROGRESS_BEFORE_FINISH
FINISH_POINT_MIN_GAP_METERS = settings.FINISH_POINT_MIN_GAP_METERS
DISAPPEAR_GAP_METERS = settings.DISAPPEAR_GAP_METERS
ABANDON_STALL_SEC = settings.ABANDON_STALL_SEC
ABANDON_MIN_PROGRESS_FOR_WIN = settings.ABANDON_MIN_PROGRESS_FOR_WIN
ABANDON_MIN_PROGRESS_METERS = settings.ABANDON_MIN_PROGRESS_METERS
SPLINE_STUCK_EPS = settings.SPLINE_STUCK_EPS
SPLINE_STUCK_SEC = settings.SPLINE_STUCK_SEC
SPLINE_STUCK_MIN_SPEED_KMH = settings.SPLINE_STUCK_MIN_SPEED_KMH
POSITION_ROLE_ASSIGN_WAIT_SEC = settings.POSITION_ROLE_ASSIGN_WAIT_SEC
SPLINE_MIN_MOVE_METERS = settings.SPLINE_MIN_MOVE_METERS
POSITION_AHEAD_MIN_METERS = settings.POSITION_AHEAD_MIN_METERS
SPLINE_INVALID_EPS = settings.SPLINE_INVALID_EPS
ABANDON_PULLAWAY_SPEED_DELTA_KMH = settings.ABANDON_PULLAWAY_SPEED_DELTA_KMH

# ── Overtake / recovery ──
OVERTAKE_POINT_COOLDOWN_SEC = settings.OVERTAKE_POINT_COOLDOWN_SEC
OVERTAKE_MIN_GAP_METERS = settings.OVERTAKE_MIN_GAP_METERS
OVERTAKE_MAX_GAP_METERS = settings.OVERTAKE_MAX_GAP_METERS
OVERTAKE_MAX_GAP_FALLBACK_METERS = settings.OVERTAKE_MAX_GAP_FALLBACK_METERS
OVERTAKE_MARGIN_SPLINE = settings.OVERTAKE_MARGIN_SPLINE
OVERTAKE_PASS_MARGIN_SPLINE = settings.OVERTAKE_PASS_MARGIN_SPLINE
OVERTAKE_ACTIVE_GRACE_SEC = settings.OVERTAKE_ACTIVE_GRACE_SEC

ROLE_ASSIGN_MIN_GAP_SPLINE = settings.ROLE_ASSIGN_MIN_GAP_SPLINE
ROLE_ASSIGN_WAIT_SEC = settings.ROLE_ASSIGN_WAIT_SEC

# ── Pair lifecycle ──
PAIR_STICKY_TIMEOUT_SEC = settings.PAIR_STICKY_TIMEOUT_SEC
PAIR_IDLE_SEPARATED_RELEASE_SEC = settings.PAIR_IDLE_SEPARATED_RELEASE_SEC
PAIR_MAX_PREACTIVE_LOCK_SEC = settings.PAIR_MAX_PREACTIVE_LOCK_SEC

# ── HUD SSE gate ──
BATTLE_REQUIRE_HUD_SSE = settings.BATTLE_REQUIRE_HUD_SSE
BATTLE_CHAT_ENABLED = settings.BATTLE_CHAT_ENABLED
