services:
  telemetry-data:
    build:
      context: ./telemetry-data
      dockerfile: Dockerfile.dev
    container_name: assetto-telemetry-data
    env_file:
      - path: ./.env.local
        required: true
    volumes:
      - ./telemetry-data:/app
      - /home/jose/assetto-install/assetto/server:/home/jose/assetto-install/assetto/server:ro
      - /home/jose/assetto-install/assetto/server-timeattack:/home/jose/assetto-install/assetto/server-timeattack:ro
    network_mode: host
    restart: unless-stopped
    command: python -m main