"""Centralized environment configuration for telemetry-data."""

from __future__ import annotations

import os

from core import env_loader  # noqa: F401 — loads ASSETTO_ENV_FILE / .env.local|.production


def _env_bool(name: str, default: str = "false") -> bool:
    return os.getenv(name, default).strip().lower() in ("1", "true", "yes", "on")


def _env_int(name: str, default: str) -> int:
    return int(os.getenv(name, default))


def _env_float(name: str, default: str) -> float:
    return float(os.getenv(name, default))


AC_INSTANCE_ID = os.getenv("AC_INSTANCE_ID", "default").strip() or "default"

_TELEMETRY_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
TELEMETRY_STATE_DIR = os.getenv("TELEMETRY_STATE_DIR", _TELEMETRY_ROOT).strip() or _TELEMETRY_ROOT
REDIS_APPLIED_CONFIG_VERSIONS_FILE = os.path.join(
    TELEMETRY_STATE_DIR, "redis_applied_config_versions.json"
)

REDIS_HOST = os.getenv("REDIS_HOST", "").strip()
REDIS_PORT = _env_int("REDIS_PORT", "6379")
REDIS_USERNAME = os.getenv("REDIS_USERNAME", "").strip() or None
REDIS_PASSWORD = os.getenv("REDIS_PASSWORD", "").strip() or None
REDIS_DB = _env_int("REDIS_DB", "0")
REDIS_SSL = _env_bool("REDIS_SSL", "false")
# Normal commands (GET/XADD). 0 = no socket read timeout.
REDIS_SOCKET_TIMEOUT_SEC = _env_int("REDIS_SOCKET_TIMEOUT_SEC", "10")
# Blocking consumers (XREADGROUP BLOCK, pub/sub). Must stay 0 (unlimited) for long BLOCK waits.
REDIS_BLOCKING_SOCKET_TIMEOUT_SEC = _env_int("REDIS_BLOCKING_SOCKET_TIMEOUT_SEC", "0")
REDIS_HEALTH_CHECK_INTERVAL_SEC = _env_int("REDIS_HEALTH_CHECK_INTERVAL_SEC", "30")
REDIS_CONFIG_XREAD_BLOCK_MS = _env_int("REDIS_CONFIG_XREAD_BLOCK_MS", "5000")

REDIS_STREAM_KEY = os.getenv("REDIS_STREAM_KEY", "ac:events").strip()
REDIS_CONFIG_STREAM_KEY = os.getenv("REDIS_CONFIG_STREAM_KEY", "ac:config").strip() or REDIS_STREAM_KEY
REDIS_STREAM_MAXLEN = _env_int("REDIS_STREAM_MAXLEN", "200000")
REDIS_SCHEMA_VERSION = os.getenv("REDIS_SCHEMA_VERSION", "1")

REDIS_CONFIG_CONSUMER_ENABLED = _env_bool("REDIS_CONFIG_CONSUMER_ENABLED", "true")
REDIS_CONFIG_CONSUMER_GROUP = os.getenv("REDIS_CONFIG_CONSUMER_GROUP", "ac-config-consumers").strip()
REDIS_CONFIG_CONSUMER_NAME = os.getenv(
    "REDIS_CONFIG_CONSUMER_NAME", f"py-{AC_INSTANCE_ID}"
).strip()

LOG_LEVEL = os.getenv("LOG_LEVEL", "INFO").strip().upper()

GHOST_DRIVER_TIMEOUT_MS = _env_int("GHOST_DRIVER_TIMEOUT_MS", "90000")
GHOST_CARINFO_DEBOUNCE_MS = _env_int("GHOST_CARINFO_DEBOUNCE_MS", "2000")
MIN_VALID_LAP_MS = _env_int("MIN_VALID_LAP_MS", "10000")
REGISTRATION_REFRESH_MIN_MS = _env_int("REGISTRATION_REFRESH_MIN_MS", "5000")
CAR_UPDATE_WATCHDOG_MS = _env_int("CAR_UPDATE_WATCHDOG_MS", "3000")

SERVER_STATUS_POLL_INTERVAL_SEC = _env_int("SERVER_STATUS_POLL_INTERVAL_SEC", "15")
SERVER_STATUS_PUBLISH_INTERVAL_SEC = _env_int("SERVER_STATUS_PUBLISH_INTERVAL_SEC", "30")
SERVER_STATUS_HEARTBEAT_INTERVAL_SEC = _env_int("SERVER_STATUS_HEARTBEAT_INTERVAL_SEC", "300")
SERVER_STATUS_ON_CHANGE_ONLY = _env_bool("SERVER_STATUS_ON_CHANGE_ONLY", "true")

REDIS_PUBLISH_QUEUE_SIZE = _env_int("REDIS_PUBLISH_QUEUE_SIZE", "4096")
REDIS_PUBLISH_WORKERS = _env_int("REDIS_PUBLISH_WORKERS", "1")

BATTLE_HUD_ENABLED = _env_bool("BATTLE_HUD_ENABLED", "true")
BATTLE_CHAT_ENABLED = _env_bool("BATTLE_CHAT_ENABLED", "true")
HUD_BATTLE_TTL_SEC = _env_int("HUD_BATTLE_TTL_SEC", "120")
HUD_BATTLE_DEBOUNCE_MS = _env_int("HUD_BATTLE_DEBOUNCE_MS", "300")
HUD_BATTLE_CLEAR_DELAY_SEC = _env_int("HUD_BATTLE_CLEAR_DELAY_SEC", "5")
HUD_VER_TTL_SEC = _env_int("HUD_VER_TTL_SEC", "3600")

# Require overlay SSE (/hud/stream) for battle matchmaking when true.
BATTLE_REQUIRE_HUD_SSE = _env_bool("BATTLE_REQUIRE_HUD_SSE", "false")
HUD_SSE_REDIS_PREFIX = os.getenv("HUD_SSE_REDIS_PREFIX", "ac:hud:sse:").strip()

USER_PREFS_SAVE_TIME_PREFIX = os.getenv(
    "USER_PREFS_SAVE_TIME_PREFIX", "ac:user:prefs:save_time:"
).strip()
USER_PREFS_ACCEPT_BATTLE_PREFIX = os.getenv(
    "USER_PREFS_ACCEPT_BATTLE_PREFIX", "ac:user:prefs:accept_battle:"
).strip()
USER_PREFS_NOTIFY_CHANNEL = os.getenv("USER_PREFS_NOTIFY_CHANNEL", "ac:user:prefs:notify").strip()
USER_PREFS_NOTIFY_ENABLED = _env_bool("USER_PREFS_NOTIFY_ENABLED", "true")
USER_PREFS_ACCEPT_BATTLE_ENABLED_MESSAGE = os.getenv(
    "USER_PREFS_ACCEPT_BATTLE_ENABLED_MESSAGE",
    "Battles enabled — you can be matched with rivals.",
).strip()
USER_PREFS_ACCEPT_BATTLE_DISABLED_MESSAGE = os.getenv(
    "USER_PREFS_ACCEPT_BATTLE_DISABLED_MESSAGE",
    "Battles disabled — you will not be matched with rivals.",
).strip()

USER_BAN_ENABLED = _env_bool("USER_BAN_ENABLED", "true")
USER_INVALIDATED_REDIS_PREFIX = os.getenv(
    "USER_INVALIDATED_REDIS_PREFIX", "ac:user:invalidated:"
).strip()
USER_INVALIDATED_CHANNEL = os.getenv("USER_INVALIDATED_CHANNEL", "ac:user:invalidated").strip()
USER_INVALIDATED_TTL_SEC = _env_int("USER_INVALIDATED_TTL_SEC", "86400")
# Wait for ac-data player_join → Convex refresh before kicking on connect
USER_BAN_DEFER_POLL_MS = _env_int("USER_BAN_DEFER_POLL_MS", "250")
USER_BAN_DEFER_ATTEMPTS = _env_int("USER_BAN_DEFER_ATTEMPTS", "8")
USER_INVALIDATED_KICK_MESSAGE = os.getenv(
    "USER_INVALIDATED_KICK_MESSAGE",
    "Your account has been deactivated from all servers.",
).strip()
USER_KICK_WARN_DELAY_SEC = _env_float(
    "USER_KICK_WARN_DELAY_SEC",
    os.getenv("USER_NOT_REGISTERED_WARN_DELAY_SEC", "3"),
)

USER_REGISTRATION_REQUIRED = _env_bool("USER_REGISTRATION_REQUIRED", "true")
USER_NOT_REGISTERED_REDIS_PREFIX = os.getenv(
    "USER_NOT_REGISTERED_REDIS_PREFIX", "ac:user:not_registered:"
).strip()
USER_NOT_REGISTERED_CHANNEL = os.getenv(
    "USER_NOT_REGISTERED_CHANNEL", "ac:user:not_registered"
).strip()
USER_NOT_REGISTERED_TTL_SEC = _env_int("USER_NOT_REGISTERED_TTL_SEC", "86400")
USER_NOT_REGISTERED_KICK_MESSAGE = os.getenv(
    "USER_NOT_REGISTERED_KICK_MESSAGE",
    "You need a ProjectD account and link Steam to play on this server.",
).strip()
USER_NOT_REGISTERED_WARN_DELAY_SEC = _env_float(
    "USER_NOT_REGISTERED_WARN_DELAY_SEC",
    str(USER_KICK_WARN_DELAY_SEC),
)

# ── Battle engine tuning (re-exported in engines/battlesystem/config.py) ──
BATTLE_ARM_MAX_GAP_METERS = _env_float("BATTLE_ARM_MAX_GAP_METERS", "15.0")
BATTLE_ARM_MIN_SPEED_KMH = _env_float("BATTLE_ARM_MIN_SPEED_KMH", "40.0")
ARM_SUSTAINED_PROXIMITY_SEC = _env_float("BATTLE_ARM_SUSTAINED_PROXIMITY_SEC", "5.0")
ARMED_CHAT_COOLDOWN_SEC = _env_float("BATTLE_ARMED_CHAT_COOLDOWN_SEC", "15.0")

MAX_BATTLE_GAP_METERS = _env_float("MAX_BATTLE_GAP_METERS", "80.0")
PRESTART_GAP_ABORT_GRACE_SEC = _env_float("BATTLE_PRESTART_GAP_ABORT_GRACE_SEC", "2.0")
GAP_ABORT_MIN_BOTH_SPEED_KMH = _env_float("BATTLE_GAP_ABORT_MIN_BOTH_SPEED_KMH", "20.0")
LAUNCH_TIMEOUT_SEC = _env_float("BATTLE_LAUNCH_TIMEOUT_SEC", "8.0")
FINISHED_COOLDOWN_SEC = _env_float("BATTLE_FINISHED_COOLDOWN_SEC", "20.0")

FINISH_LINE_HIGH_SPLINE = _env_float("BATTLE_FINISH_LINE_HIGH_SPLINE", "0.90")
FINISH_LINE_LOW_SPLINE = _env_float("BATTLE_FINISH_LINE_LOW_SPLINE", "0.10")
MIN_LAP_PROGRESS_BEFORE_FINISH = _env_float(
    "BATTLE_MIN_LAP_PROGRESS_BEFORE_FINISH",
    os.getenv("RUN_END_SPLINE_FRACTION", "0.30"),
)
FINISH_POINT_MIN_GAP_METERS = _env_float("BATTLE_FINISH_POINT_MIN_GAP_METERS", "20.0")
DISAPPEAR_GAP_METERS = _env_float("BATTLE_DISAPPEAR_GAP_METERS", "250.0")
ABANDON_STALL_SEC = _env_float("BATTLE_ABANDON_STALL_SEC", "5.0")
ABANDON_MIN_PROGRESS_FOR_WIN = _env_float("BATTLE_ABANDON_MIN_PROGRESS_FOR_WIN", "0.10")
ABANDON_MIN_PROGRESS_METERS = _env_float("BATTLE_ABANDON_MIN_PROGRESS_METERS", "200.0")
SPLINE_STUCK_EPS = _env_float("BATTLE_SPLINE_STUCK_EPS", "0.0001")
SPLINE_STUCK_SEC = _env_float("BATTLE_SPLINE_STUCK_SEC", "2.0")
SPLINE_STUCK_MIN_SPEED_KMH = _env_float(
    "BATTLE_SPLINE_STUCK_MIN_SPEED_KMH",
    str(min(25.0, BATTLE_ARM_MIN_SPEED_KMH)),
)
POSITION_ROLE_ASSIGN_WAIT_SEC = _env_float("BATTLE_POSITION_ROLE_ASSIGN_WAIT_SEC", "0.5")
SPLINE_MIN_MOVE_METERS = _env_float("BATTLE_SPLINE_MIN_MOVE_METERS", "5.0")
POSITION_AHEAD_MIN_METERS = _env_float("BATTLE_POSITION_AHEAD_MIN_METERS", "2.0")
SPLINE_INVALID_EPS = _env_float("BATTLE_SPLINE_INVALID_EPS", "0.001")
ABANDON_PULLAWAY_SPEED_DELTA_KMH = _env_float("BATTLE_ABANDON_PULLAWAY_SPEED_DELTA_KMH", "15.0")

OVERTAKE_POINT_COOLDOWN_SEC = _env_float("OVERTAKE_POINT_COOLDOWN_SEC", "2.0")
OVERTAKE_MIN_GAP_METERS = _env_float("OVERTAKE_MIN_GAP_METERS", "10.0")
OVERTAKE_MAX_GAP_METERS = _env_float("OVERTAKE_MAX_GAP_METERS", "15.0")
OVERTAKE_MAX_GAP_FALLBACK_METERS = _env_float("BATTLE_OVERTAKE_MAX_GAP_FALLBACK_METERS", "20.0")
OVERTAKE_MARGIN_SPLINE = _env_float("BATTLE_OVERTAKE_MARGIN_SPLINE", "0.005")
OVERTAKE_PASS_MARGIN_SPLINE = _env_float("BATTLE_OVERTAKE_PASS_MARGIN_SPLINE", "0.0003")
OVERTAKE_ACTIVE_GRACE_SEC = _env_float("BATTLE_OVERTAKE_ACTIVE_GRACE_SEC", "2.0")

ROLE_ASSIGN_MIN_GAP_SPLINE = _env_float("BATTLE_ROLE_ASSIGN_MIN_GAP_SPLINE", "0.0006")
ROLE_ASSIGN_WAIT_SEC = _env_float("BATTLE_ROLE_ASSIGN_WAIT_SEC", "6.0")

PAIR_STICKY_TIMEOUT_SEC = _env_float("BATTLE_PAIR_STICKY_TIMEOUT_SEC", "20.0")
PAIR_IDLE_SEPARATED_RELEASE_SEC = _env_float("BATTLE_PAIR_IDLE_SEPARATED_RELEASE_SEC", "10.0")
PAIR_MAX_PREACTIVE_LOCK_SEC = _env_float("BATTLE_PAIR_MAX_PREACTIVE_LOCK_SEC", "120.0")
