FROM node:20-alpine

WORKDIR /app

RUN apk add --no-cache git bash

COPY package*.json ./
RUN npm ci

RUN npm install typescript tsx

COPY . .

ENV SERVERS_PATH=/home/jose/assetto-install/assetto/server
ENV PORT=3000

EXPOSE 3000

CMD ["npx", "tsx", "src/index.ts"]