FROM python:3.11-slim

WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends \
    git \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

ENV SERVERS_PATH=/home/jose/assetto-install/assetto/server
ENV AC_INSTANCE_ID=vps-eu-2

CMD ["python", "-m", "main"]